#!/usr/bin/env bash
# Bash script displays DNS records: record type, IP, subdomains

print_w ()
{
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]; then
   for subs in "www" "lb-01" "web-01" "web-02"
   do
       print_w "$1" "$subs"
   done
else
    print_w "$1" "$2"
fi