#!/usr/bin/env bash
#A Bash script that will display information about subdomains.

display_info() {
    local domain=$1
    local subdomain=$2

    local subdomains=()
    if [[ -n "$subdomain" ]]; then
        subdomains=("$subdomain")
    else
        subdomains=("www" "lb-01" "web-01" "web-02")
    fi

    local record_type destination

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "${sub}.${domain}" +short)
        destination=$(dig "${sub}.${domain}" | grep -A1 'ANSWER SECTION:' | awk '/A/{print $5}')
        echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
    done
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2

display_info "$domain" "$subdomain"
