#!/usr/bin/env bash
#Let's install nginx.

sudo apt-get update -y

sudo apt-get install nginx -y

sudo service nginx start

echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html

