#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me return 301 alialx.tech permanent;' sudo  tee /etc/nginx/sites-available/default

