#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task.

# Get the hostname
hostname=$(hostname)

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Modify Nginx default configuration to include custom header
sudo sed -i "s|^\s*server_name\s\+_;$|\0\n\tadd_header X-Served-By $hostname;|" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
