#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task.

# Get the hostname
hostname=$(hostname)

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a custom Nginx configuration
custom_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header X-Served-By $hostname;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
}
"

# Write the custom configuration to a new file
echo "$custom_config" | sudo tee /etc/nginx/sites-available/custom_config

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_config /etc/nginx/sites-enabled/

# Remove the default Nginx site configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
