#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task.

sudo apt-get update

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html /var/www/error

sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html

echo "this is the wrong page" > /var/www/html/404.html

server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://twitter.com/Alijr_2018 permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart