#!/usr/bin/env bash                                                           
# Install and configure HAproxy on your lb-01 server.                        

sudo apt-get update

sudo apt-get install -y haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    maxconn 2000
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout http-request 10s
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout check 10s
    maxconn 3000

frontend main
    bind *:80
    default_backend app_servers

backend app_servers
    balance roundrobin
    server web-01 387398-web-01:80 check
    server web-02 387398-web-02:80 check
EOL

sudo systemctl restart haproxy


sudo bash -c "echo '52.205.94.206 387398-web-02' >> /etc/hosts"
sudo bash -c "echo '52.86.161.51 387398-web-02' >> /etc/hosts"
