#!/usr/bin/env bash
# This script that :
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


function handle_sigterm_quit
{
    echo "I hate the kill command"
    cleanup_and_exit
}

function handle_sigint
{
    echo "Y U no love me?!"
}

function cleanup_and_exit
{
    
    if [ -f "/var/run/myscript.pid" ]; then
        rm "/var/run/myscript.pid"
    fi
    exit 0
}

trap handle_sigterm_quit SIGTERM SIGQUIT
trap handle_sigint SIGINT

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 1
done

cleanup_and_exit