#!/usr/bin/env bash
# This script that manages manage_my_process


# Function to start the manage_my_process script
function start_process {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "manage_my_process is already started."
        exit 1
    fi

    ./manage_my_process &
    pid=$!
    echo "$pid" > /var/run/my_process.pid
    echo "manage_my_process started"
}

# Function to stop the manage_my_process script
function stop_process {
    if [ -f "/var/run/my_process.pid" ]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm "/var/run/my_process.pid"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
        exit 1
    fi
}

# Function to restart the manage_my_process script
function restart_process {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

# Check the argument and call the appropriate function
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
