#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user

while IFS=':' read -r username _ uid _ home _
do
    echo "$username:$uid:$home"
done < /etc/passwd
